// Redir admin — IIFE, no globals.
(()=>{const sb=supabase.createClient(SUPABASE.url,SUPABASE.publishableKey),$=id=>document.getElementById(id),ready=!SUPABASE.url.includes('YOUR-'),list=$('t').tBodies[0];let returnY=null
$('status').innerHTML=ready?`✅ ${SUPABASE.url}`:'⚠️ Configure <b>db.js</b> (URL + publishable key) — see "Setup" below.'
const load=async()=>{let q=await sb.from('redir').select('id,url,"desc","group",sort,qr,present').order('sort').order('sort','id');if(q.error)q=await sb.from('redir').select('id,url,"desc","group",sort').order('sort').order('sort','id');const{data,error}=q;$('msg').textContent=error?.message||'';list.innerHTML=(data||[]).map(r=>`<tr data-id="${r.id}" data-url="${r.url}" data-desc="${r.desc||''}" data-group="${r.group||''}" data-sort="${r.sort??''}" data-qr="${r.qr||''}" data-present="${r.present||''}"><td>${r.id}</td><td><a target=_blank rel=noopener href="${r.url}">${r.url}</a></td><td>${r.desc||''}</td><td>${r.group||''}</td><td>${r.sort??''}</td><td>${r.qr||''}</td><td>${r.present||''}</td><td><button data-e>✎</button><button data-d>🗑</button></td></tr>`).join('')}
$('t').onclick=e=>{const tr=e.target.closest('tr'),b=e.target.closest('button');if(!tr||!b)return;b.hasAttribute('data-e')?(returnY=scrollY,$('id').value=tr.dataset.id,$('url').value=tr.dataset.url,$('desc').value=tr.dataset.desc,$('group').value=tr.dataset.group,$('sort').value=tr.dataset.sort,$('id').dataset.o=tr.dataset.id,$('cancel').hidden=false,openEd(tr.dataset.id),scrollTo({top:0,behavior:'smooth'})):b.hasAttribute('data-d')&&confirm(`Delete ${tr.dataset.id}?`)&&sb.from('redir').delete().eq('id',tr.dataset.id).then(load)}
const ed=$('ed'),prs=$('present'),qrpick=$('qrpick'),qrfr=$('qrfr'),qrbox=$('qrbox'),imgbox=$('imgbox'),artimg=$('artimg'),artlink=$('artlink');let edId='',edSel='',edNew=true,idT=null
const patch=async(id,body)=>{const{data,error}=await sb.from('redir').update(body).eq('id',id).select('id');return error?error.message:(data&&data.length?'':`no row ${id}: needs the anon UPDATE policy`)}
const rowOf=id=>[...list.querySelectorAll('tr')].find(r=>r.dataset.id===id)
const loadQr=()=>{qrfr.dataset.for=edId;qrfr.src='i/u/qr.html?'+(/u$/.test(edSel)?'x21=U&':'')+'ex=1&v=O&sel='+encodeURIComponent(edSel)+'&x='+encodeURIComponent(edId)}
const loadImg=()=>{const u='i/'+edId+'.png';imgbox.hidden=false;$('imgmsg').textContent='';artimg.classList.remove('miss');artimg.alt=edId;artlink.href=u;artimg.src=u}
artimg.onerror=()=>{artimg.classList.add('miss');$('imgmsg').textContent='i/'+edId+'.png not found'}
const syncPrs=()=>{const v=prs.value;qrbox.hidden=v!=='qr';imgbox.hidden=v!=='img';if(v!=='qr'){qrfr.removeAttribute('src');qrfr.dataset.for=''}else if(qrfr.dataset.for!==edId)loadQr();if(v==='img')loadImg();else{artimg.removeAttribute('src');artimg.classList.remove('miss');$('imgmsg').textContent=''}}
const openEd=(id,isNew)=>{edId=id;edNew=!!isNew;ed.hidden=false;const tr=rowOf(id);edSel=(!edNew&&tr&&tr.dataset.qr)||'';prs.value=(!edNew&&tr&&tr.dataset.present)||'img';$('prsmsg').textContent=edNew?'new — applied on Save':'';$('qrmsg').textContent='';qrpick.innerHTML='<option value="">— none —</option>';qrfr.dataset.for='';syncPrs()}
const closeEd=()=>{edId='';ed.hidden=true;qrfr.removeAttribute('src');qrfr.dataset.for='';artimg.removeAttribute('src')}
$('id').oninput=()=>{clearTimeout(idT);idT=setTimeout(()=>{const v=$('id').value.trim();if(!v){if(edNew)closeEd();return}openEd(v,!rowOf(v))},350)}
prs.onchange=()=>{if(!edId)return;syncPrs();if(edNew)return void($('prsmsg').textContent='new — applied on Save');$('prsmsg').textContent='saving…';(async()=>{const m=await patch(edId,{present:prs.value});$('prsmsg').textContent=m||('present: '+prs.value);if(!m)await load()})()}
const saveQr=v=>{if(!edId)return;edSel=v||'';if(edNew)return void($('qrmsg').textContent='new — applied on Save');$('qrmsg').textContent='saving…';(async()=>{const m=await patch(edId,{qr:edSel||null});$('qrmsg').textContent=m||(edSel?'saved '+edSel:'cleared');if(!m)await load()})()}
qrpick.onchange=()=>saveQr(qrpick.value)
window.addEventListener('message',e=>{const d=e.data;if(!d||!d.x||d.x!==edId)return;if(d.type==='qr-pick'){if(![].some.call(qrpick.options,o=>o.value===d.lab))qrpick.insertAdjacentHTML('afterbegin','<option value="'+d.lab+'">'+d.lab+'</option>');qrpick.value=d.lab;return saveQr(d.lab)}if(d.type!=='qr-tiles')return;const seen={},opts=[],tw={};const add=l=>{if(!l||seen[l])return;seen[l]=1;opts.push(l);if(l.slice(0,2)==='21'){const t=l.slice(-1)==='u'?l.slice(0,-1):l+'u';if(!seen[t]){seen[t]=1;opts.push(t);tw[t]=l}}};(d.recs||[]).forEach(add);(d.tiles||[]).forEach(t=>add(t.lab));if(d.sel&&opts.indexOf(d.sel)<0)opts.unshift(d.sel);const rec=new Set(d.recs||[]);qrpick.innerHTML=opts.map(l=>`<option value="${l}">${l}${rec.has(l)||rec.has(tw[l])?' ★':''}</option>`).join('')||'<option value="">— none —</option>';qrpick.value=opts.indexOf(d.sel)>=0?d.sel:''})
$('cancel').onclick=()=>{$('f').reset();$('id').dataset.o='';$('cancel').hidden=true;closeEd();if(returnY!==null)scrollTo({top:returnY,behavior:'smooth'});returnY=null}
const sep=(1.1).toLocaleString().replace(/[\d\s]/g,'')===','?';':','
const dlCSV=async t=>{const{data,error}=await sb.from(t).select('*');if(error)return $('msg').textContent=error.message;if(!data.length)return $('msg').textContent=`${t}: empty`;const cols=Object.keys(data[0]),esc=v=>{if(v==null)return'';if(typeof v==='object')v=JSON.stringify(v);v=String(v);return v.includes(sep)||/[\t\n"]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v};const csv='\uFEFF'+cols.join(sep)+'\n'+data.map(r=>cols.map(c=>esc(r[c])).join(sep)).join('\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=t+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100)}
const truncate=async t=>{await sb.from(t).delete().neq('id','-1')}
$('bk-redir').onclick=async()=>{await dlCSV('redir');$('trunc-export').checked&&confirm('Truncate redir after export?')&&await truncate('redir')}
$('bk-log').onclick=async()=>{await dlCSV('log');$('trunc-export').checked&&confirm('Truncate log after export?')&&await truncate('log')}
const splitRow=l=>{const f=[],c=[];let q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){c.push('"');i++}else q=!q}else if(ch===sep&&!q){f.push(c.join(''));c.length=0}else c.push(ch)}f.push(c.join(''));return f}
const parseCSV=txt=>{const L=txt.replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').filter(x=>x.trim()!=='');if(L.length<2)return[];const cols=splitRow(L[0]);return L.slice(1).map(l=>{const v=splitRow(l),o={};cols.forEach((c,i)=>{let x=v[i];if(x==='')x=null;else if(x&&/^[\[{]/.test(x)){try{x=JSON.parse(x)}catch(e){}}o[c]=x});return o})}
let impTable=''
$('im-redir').onclick=()=>{impTable='redir';$('imp-file').click()}
$('im-log').onclick=()=>{impTable='log';$('imp-file').click()}
$('imp-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const rows=parseCSV(await f.text());if(!rows.length)return $('msg').textContent='No rows';const merge=$('merge-imp').checked;if(impTable==='log'){rows.forEach(r=>delete r.id);if(!merge)await sb.from('log').delete().neq('id','-1');const{error}=await sb.from('log').insert(rows);$('msg').textContent=error?.message||`Imported ${rows.length} into log`}else{if(!merge)await sb.from('redir').delete().neq('id','-1');const{error}=await sb.from('redir').upsert(rows,{onConflict:'id'});$('msg').textContent=error?.message||`Imported ${rows.length} into redir`;if(!error)await load()}}
$('f').onsubmit=e=>{e.preventDefault();if(!ready)return $('status').innerHTML='⚠️ Fill in <b>db.js</b> first';const id=$('id').value,u=$('url').value,d=$('desc').value,g=$('group').value,s=$('sort').value,o=$('id').dataset.o||'';(async()=>{if(o&&o!==id)await sb.from('redir').delete().eq('id',o);const pv=edId===id?{present:prs.value,qr:edSel||null}:{};const{error}=await(o&&o===id?sb.from('redir').update({url:u,desc:d,group:g||null,sort:s?+s:null,...pv}).eq('id',id):sb.from('redir').insert({id,url:u,desc:d,group:g||null,sort:s?+s:null,...pv}));$('msg').textContent=error?.message||'';if(!error){$('f').reset();$('id').dataset.o='';$('cancel').hidden=true;closeEd();load();if(returnY!==null)scrollTo({top:returnY,behavior:'smooth'});returnY=null}})()}
const q=new URLSearchParams(location.search).get('add'),todo=q?(()=>{try{return Object.entries(JSON.parse(q))}catch(e){return []}})():[]
if(todo.length)(async()=>{let n=0,err='';for(const[id,url]of todo){const{error}=await sb.from('redir').upsert({id,url},{onConflict:'id'});error?err=error.message:n++}history.replaceState({},'',location.pathname);await load();$('msg').textContent=err||`Added/updated ${n} songs`})()
else ready&&load()})()
