// Redir admin — IIFE, no globals.
(()=>{const sb=supabase.createClient(SUPABASE.url,SUPABASE.publishableKey),$=id=>document.getElementById(id),ready=!SUPABASE.url.includes('YOUR-'),list=$('t').tBodies[0];let returnY=null
$('status').innerHTML=ready?`✅ ${SUPABASE.url}`:'⚠️ Configure <b>db.js</b> (URL + publishable key) — see "Setup" below.'
const load=async()=>{const{data,error}=await sb.from('redir').select('id,url,"desc","group",sort').order('sort').order('sort','id');$('msg').textContent=error?.message||'';list.innerHTML=(data||[]).map(r=>`<tr data-id="${r.id}" data-url="${r.url}" data-desc="${r.desc||''}" data-group="${r.group||''}" data-sort="${r.sort??''}"><td>${r.id}</td><td><a target=_blank rel=noopener href="${r.url}">${r.url}</a></td><td>${r.desc||''}</td><td>${r.group||''}</td><td>${r.sort??''}</td><td><button data-e>✎</button><button data-d>🗑</button></td></tr>`).join('')}
$('t').onclick=e=>{const tr=e.target.closest('tr'),b=e.target.closest('button');if(!tr||!b)return;b.hasAttribute('data-e')?(returnY=scrollY,$('id').value=tr.dataset.id,$('url').value=tr.dataset.url,$('desc').value=tr.dataset.desc,$('group').value=tr.dataset.group,$('sort').value=tr.dataset.sort,$('id').dataset.o=tr.dataset.id,$('cancel').hidden=false,scrollTo({top:0,behavior:'smooth'})):b.hasAttribute('data-d')&&confirm(`Delete ${tr.dataset.id}?`)&&sb.from('redir').delete().eq('id',tr.dataset.id).then(load)}
$('cancel').onclick=()=>{$('f').reset();$('id').dataset.o='';$('cancel').hidden=true;if(returnY!==null)scrollTo({top:returnY,behavior:'smooth'});returnY=null}
const sep=(1.1).toLocaleString().replace(/[\d\s]/g,'')===','?';':','
const dlCSV=async t=>{const{data,error}=await sb.from(t).select('*');if(error)return $('msg').textContent=error.message;if(!data.length)return $('msg').textContent=`${t}: empty`;const cols=Object.keys(data[0]),esc=v=>{if(v==null)return'';if(typeof v==='object')v=JSON.stringify(v);v=String(v);return v.includes(sep)||/[\t\n"]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v};const csv='\uFEFF'+cols.join(sep)+'\n'+data.map(r=>cols.map(c=>esc(r[c])).join(sep)).join('\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=t+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100)}
const truncate=async t=>{await sb.from(t).delete().neq('id','-1')}
$('bk-redir').onclick=async()=>{await dlCSV('redir');$('trunc-export').checked&&confirm('Truncate redir after export?')&&await truncate('redir')}
$('bk-log').onclick=async()=>{await dlCSV('log');$('trunc-export').checked&&confirm('Truncate log after export?')&&await truncate('log')}
const splitRow=l=>{const f=[],c=[];let q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){c.push('"');i++}else q=!q}else if(ch===sep&&!q){f.push(c.join(''));c.length=0}else c.push(ch)}f.push(c.join(''));return f}
const parseCSV=txt=>{const L=txt.replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').filter(x=>x.trim()!=='');if(L.length<2)return[];const cols=splitRow(L[0]);return L.slice(1).map(l=>{const v=splitRow(l),o={};cols.forEach((c,i)=>{let x=v[i];if(x==='')x=null;else if(x&&/^[\[{]/.test(x)){try{x=JSON.parse(x)}catch(e){}}o[c]=x});return o})}
let impTable=''
$('im-redir').onclick=()=>{impTable='redir';$('imp-file').click()}
$('im-log').onclick=()=>{impTable='log';$('imp-file').click()}
$('imp-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const rows=parseCSV(await f.text());if(!rows.length)return $('msg').textContent='No rows';const merge=$('merge-imp').checked;if(impTable==='log'){rows.forEach(r=>delete r.id);if(!merge)await sb.from('log').delete().neq('id','-1');const{error}=await sb.from('log').insert(rows);$('msg').textContent=error?.message||`Imported ${rows.length} into log`}else{if(!merge)await sb.from('redir').delete().neq('id','-1');const{error}=await sb.from('redir').upsert(rows,{onConflict:'id'});$('msg').textContent=error?.message||`Imported ${rows.length} into redir`;if(!error)await load()}}
$('f').onsubmit=e=>{e.preventDefault();if(!ready)return $('status').innerHTML='⚠️ Fill in <b>db.js</b> first';const id=$('id').value,u=$('url').value,d=$('desc').value,g=$('group').value,s=$('sort').value,o=$('id').dataset.o||'';(async()=>{if(o&&o!==id)await sb.from('redir').delete().eq('id',o);const{error}=await(o&&o===id?sb.from('redir').update({url:u,desc:d,group:g||null,sort:s?+s:null}).eq('id',id):sb.from('redir').insert({id,url:u,desc:d,group:g||null,sort:s?+s:null}));$('msg').textContent=error?.message||'';if(!error){$('f').reset();$('id').dataset.o='';$('cancel').hidden=true;load();if(returnY!==null)scrollTo({top:returnY,behavior:'smooth'});returnY=null}})()}
const q=new URLSearchParams(location.search).get('add'),todo=q?(()=>{try{return Object.entries(JSON.parse(q))}catch(e){return []}})():[]
if(todo.length)(async()=>{let n=0,err='';for(const[id,url]of todo){const{error}=await sb.from('redir').upsert({id,url},{onConflict:'id'});error?err=error.message:n++}history.replaceState({},'',location.pathname);await load();$('msg').textContent=err||`Added/updated ${n} songs`})()
else ready&&load()})()
